# Generated by Django 5.1.1 on 2024-10-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('work', 'Work'), ('other', 'Other')], default='personal', max_length=20),
        ),
    ]
