# Generated by Django 5.1.1 on 2024-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='size',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'medio'), ('grande', 'grande'), ('n/a', 'N/A')], default='N/A', max_length=20),
        ),
    ]
