# Generated by Django 5.1.1 on 2024-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_note_category_note_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='massa',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('fubá', 'Fuba'), ('cenoura', 'Cenoura'), ('n/a', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='recheio',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('morango', 'Morango'), ('caramelo', 'Caramelo'), ('n/a', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='topo',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
