# Generated by Django 5.1.1 on 2024-10-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_rename_title_note_name_alter_note_massa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='topo',
            new_name='contato',
        ),
    ]
