# Generated by Django 5.1.1 on 2024-10-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_note_recheio'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
