# Generated by Django 5.1.1 on 2024-10-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_note_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='price',
        ),
    ]
