# Generated by Django 5.1.1 on 2024-10-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_remove_note_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='massa_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='recheio_price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='size_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
