# Generated by Django 5.1.1 on 2024-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_note_massa_price_note_recheio_price_note_size_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='massa',
            field=models.CharField(choices=[('n/a', 'N/A'), ('chocolate', 'Chocolate'), ('fubá', 'Fuba'), ('cenoura', 'Cenoura')], default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='massa_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='note',
            name='recheio',
            field=models.CharField(choices=[('n/a', 'N/A'), ('chocolate', 'Chocolate'), ('morango', 'Morango'), ('caramelo', 'Caramelo')], default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='recheio_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='note',
            name='size',
            field=models.CharField(choices=[('n/a', 'N/A'), ('pequeno', 'Pequeno'), ('medio', 'medio'), ('grande', 'grande')], default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='size_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
