# Generated by Django 5.1.1 on 2024-10-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_note_massa_alter_note_massa_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='massa_price',
        ),
        migrations.RemoveField(
            model_name='note',
            name='recheio_price',
        ),
        migrations.RemoveField(
            model_name='note',
            name='size_price',
        ),
        migrations.AlterField(
            model_name='note',
            name='massa',
            field=models.CharField(choices=[('n/a', 'N/A'), ('chocolate', 'Chocolate'), ('fubá', 'Fubá'), ('cenoura', 'Cenoura')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='recheio',
            field=models.CharField(choices=[('n/a', 'N/A'), ('chocolate', 'Chocolate'), ('morango', 'Morango'), ('caramelo', 'Caramelo')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='size',
            field=models.CharField(choices=[('n/a', 'N/A'), ('pequeno', 'Pequeno'), ('medio', 'Medio'), ('grande', 'Grande')], default='N/A', max_length=20),
        ),
    ]
